name: infsplign
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accelerate=1.5.2=pyhd8ed1ab_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=h865e1df_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cython-blis=1.0.1=py311h5eee18b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - diffusers-base=0.32.2=py311h06a4308_0
  - diffusers-torch=0.32.2=py311h06a4308_0
  - einops=0.8.1=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gcc_linux-64=9.5.0=h4258300_13
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - gxx_linux-64=9.5.0=h43f449f_13
  - huggingface_accelerate=1.4.0=py311h06a4308_0
  - huggingface_hub=0.29.2=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h5eee18b_3
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lazy_loader=0.4=py311h06a4308_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsanitizer=9.5.0=h2f262e1_19
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=2.0.2=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyqt=6.7.1=py311h6a678d5_0
  - python=3.11.11=he870216_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h5eee18b_0
  - pytorch=2.4.1=py3.11_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - qtbase=6.7.2=hdaa5aa8_1
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - ruamel.yaml=0.18.6=py311h5eee18b_0
  - ruamel.yaml.clib=0.2.8=py311h5eee18b_0
  - s2n=1.3.27=hdbd6064_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py311h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=3.0.0=py311
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.11.10
    - annotated-types==0.6.0
    - attrs==24.3.0
    - blis==1.0.1
    - bottleneck==1.4.2
    - brotli==1.0.9
    - catalogue==2.0.10
    - certifi==2025.1.31
    - click==8.1.7
    - clip==1.0
    - cloudpathlib==0.16.0
    - colorama==0.4.6
    - confection==0.1.4
    - contourpy==1.3.1
    - cymem==2.0.6
    - datasets==3.3.2
    - diffusers==0.32.2
    - dill==0.3.8
    - en-core-web-sm==3.8.0
    - fastcore==1.7.20
    - filelock==3.13.1
    - fonttools==4.55.3
    - frozenlist==1.5.0
    - fsspec==2024.12.0
    - gmpy2==2.2.1
    - huggingface-hub==0.29.2
    - idna==3.7
    - imageio==2.37.0
    - importlib-metadata==8.5.0
    - inflect==7.0.0
    - ipython==8.30.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - markdown-it-py==2.2.0
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.6
    - mdurl==0.1.0
    - mkl-fft==1.3.11
    - mkl-random==1.2.8
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.15
    - murmurhash==1.0.12
    - networkx==3.4.2
    - numexpr==2.10.1
    - numpy==2.0.2
    - packaging==24.2
    - pandas==2.2.3
    - parso==0.8.4
    - pillow==11.1.0
    - pip==25.0
    - preshed==3.0.6
    - prompt-toolkit==3.0.43
    - propcache==0.2.0
    - psutil==5.9.0
    - pyarrow==19.0.0
    - pydantic==2.10.3
    - pydantic-core==2.27.1
    - pygments==2.15.1
    - pyparsing==3.2.0
    - pyqt6==6.7.1
    - pyqt6-sip==13.9.1
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - ruamel-yaml==0.18.6
    - ruamel-yaml-clib==0.2.8
    - safetensors==0.5.3
    - scikit-image==0.25.0
    - scikit-learn==1.6.1
    - scipy==1.15.1
    - setuptools==72.1.0
    - shellingham==1.5.0
    - sip==6.10.0
    - smart-open==5.2.1
    - spacy==3.8.2
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.5.1
    - sympy==1.13.3
    - tabulate==0.9.0
    - thinc==8.3.2
    - tifffile==2025.2.18
    - tokenizers==0.20.1
    - torch==2.4.1
    - torchaudio==2.4.1
    - torchvision==0.19.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.45.2
    - triton==3.0.0
    - typer==0.9.0
    - typing-extensions==4.12.2
    - unicodedata2==15.1.0
    - urllib3==2.3.0
    - wasabi==0.9.1
    - weasel==0.3.4
    - wheel==0.45.1
    - xxhash==3.5.0
    - yarl==1.18.0
    - zipp==3.21.0
